### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Anjacodes** [fabianofrank/conference-page#2]
Good job so far! Your design looks great and identical to the original design.
Here are a few tips for improvement:

- You should have an index.html file so that your page can be deployed since it's industry standard
- Set your navbar box-sizing to border-box so that you can better manage the content and its positioning.
- Consider using *{box-sizing: border-box; margin: 0;}
- Lower the padding for your header image and text

**Comment by fabianofrank** [comment]
Thanks for the brilliant issue!
